window.Modernizr=function(c,a,d){function g(){e.input=function(n){for(var a=0,b=n.length;a<b;a++)u[n[a]]=n[a]in m;return u}("autocomplete autofocus list placeholder max min multiple pattern required step".split(" "));e.inputtypes=function(n){for(var o=0,b,c,e,f=n.length;o<f;o++)m.setAttribute("type",c=n[o]),(b="text"!==m.type)&&(m.value=t,m.style.cssText="position:absolute;visibility:hidden;",/^range$/.test(c)&&m.style.WebkitAppearance!==d?(j.appendChild(m),e=a.defaultView,b=e.getComputedStyle&&"textfield"!==
e.getComputedStyle(m,null).WebkitAppearance&&0!==m.offsetHeight,j.removeChild(m)):/^(search|tel)$/.test(c)||(/^(url|email)$/.test(c)?b=m.checkValidity&&!1===m.checkValidity():/^color$/.test(c)?(j.appendChild(m),b=m.value!=t,j.removeChild(m)):b=m.value!=t)),w[n[o]]=!!b;return w}("search tel url email datetime date month week time datetime-local number range color".split(" "))}function h(n,a){var b=n.charAt(0).toUpperCase()+n.substr(1),b=(n+" "+s.join(b+" ")+b).split(" ");return q(b,a)}function q(n,
a){for(var b in n)if(k[n[b]]!==d)return"pfx"==a?n[b]:!0;return!1}function p(n,a){return typeof n===a}var e={},j=a.documentElement;a.head||a.getElementsByTagName("head");var f=a.createElement("modernizr"),k=f.style,m=a.createElement("input"),t=":)",x=Object.prototype.toString,r=" -webkit- -moz- -o- -ms- -khtml-".split(" "),s=["Webkit","Moz","O","ms","Khtml"],f={},w={},u={},z=[],B=function(n,b,c,e){var f,d=a.createElement("div");if(parseInt(c,10))for(;c--;)f=a.createElement("div"),f.id=e?e[c]:"modernizr"+
(c+1),d.appendChild(f);c=["&shy;<style>",n,"</style>"].join("");d.id="modernizr";d.innerHTML+=c;j.appendChild(d);n=b(d,n);d.parentNode.removeChild(d);return!!n},b=function(){var n={select:"input",change:"input",submit:"form",reset:"form",error:"img",load:"img",abort:"img"};return function(b,c){var c=c||a.createElement(n[b]||"div"),b="on"+b,e=b in c;e||(c.setAttribute||(c=a.createElement("div")),c.setAttribute&&c.removeAttribute&&(c.setAttribute(b,""),e=p(c[b],"function"),p(c[b],d)||(c[b]=d),c.removeAttribute(b)));
return e}}(),C,l={}.hasOwnProperty,y;!p(l,d)&&!p(l.call,d)?y=function(a,b){return l.call(a,b)}:y=function(a,b){return b in a&&p(a.constructor.prototype[b],d)};(function(b,d){var f=b.join(""),l=d.length;B(f,function(b,n){for(var d=a.styleSheets[a.styleSheets.length-1],d=d.cssRules&&d.cssRules[0]?d.cssRules[0].cssText:d.cssText||"",f=b.childNodes,o={};l--;)o[f[l].id]=f[l];e.touch="ontouchstart"in c||9===o.touch.offsetTop;e.csstransforms3d=9===o.csstransforms3d.offsetLeft;e.generatedcontent=1<=o.generatedcontent.offsetHeight;
e.fontface=/src/i.test(d)&&0===d.indexOf(n.split(" ")[0])},l,d)})(['@font-face {font-family:"font";src:url("https://")}',["@media (",r.join("touch-enabled),("),"modernizr){#touch{top:9px;position:absolute}}"].join(""),["@media (",r.join("transform-3d),("),"modernizr){#csstransforms3d{left:9px;position:absolute}}"].join(""),['#generatedcontent:after{content:"',t,'";visibility:hidden}'].join("")],["fontface","touch","csstransforms3d","generatedcontent"]);f.flexbox=function(){var b=a.createElement("div"),
c=a.createElement("div"),d;d="display:";b.style.cssText=(d+r.join("box;"+d)).slice(0,-d.length)+"width:42px;padding:0;";c.style.cssText=r.join("box-flex:1;")+"width:10px;";b.appendChild(c);j.appendChild(b);d=42===c.offsetWidth;b.removeChild(c);j.removeChild(b);return d};f.canvas=function(){var b=a.createElement("canvas");return!!b.getContext&&!!b.getContext("2d")};f.canvastext=function(){return!!e.canvas&&!!p(a.createElement("canvas").getContext("2d").fillText,"function")};f.webgl=function(){return!!c.WebGLRenderingContext};
f.touch=function(){return e.touch};f.geolocation=function(){return!!navigator.geolocation};f.postmessage=function(){return!!c.postMessage};f.websqldatabase=function(){return!!c.openDatabase};f.indexedDB=function(){for(var b=-1,a=s.length;++b<a;)if(c[s[b].toLowerCase()+"IndexedDB"])return!0;return!!c.indexedDB};f.hashchange=function(){return b("hashchange",c)&&(a.documentMode===d||7<a.documentMode)};f.history=function(){return!!c.history&&!!history.pushState};f.draganddrop=function(){return b("dragstart")&&
b("drop")};f.websockets=function(){for(var b=-1,a=s.length;++b<a;)if(c[s[b]+"WebSocket"])return!0;return"WebSocket"in c};f.rgba=function(){k.cssText="background-color:rgba(150,255,150,.5)";return!!~(""+k.backgroundColor).indexOf("rgba")};f.hsla=function(){k.cssText="background-color:hsla(120,40%,100%,.5)";return!!~(""+k.backgroundColor).indexOf("rgba")||!!~(""+k.backgroundColor).indexOf("hsla")};f.multiplebgs=function(){k.cssText="background:url(https://),url(https://),red url(https://)";return/(url\s*\(.*?){3}/.test(k.background)};
f.backgroundsize=function(){return h("backgroundSize")};f.borderimage=function(){return h("borderImage")};f.borderradius=function(){return h("borderRadius")};f.boxshadow=function(){return h("boxShadow")};f.textshadow=function(){return""===a.createElement("div").style.textShadow};f.opacity=function(){var b=r.join("opacity:.55;")+"";k.cssText=b;return/^0.55$/.test(k.opacity)};f.cssanimations=function(){return h("animationName")};f.csscolumns=function(){return h("columnCount")};f.cssgradients=function(){var b=
("background-image:"+r.join("gradient(linear,left top,right bottom,from(#9f9),to(white));background-image:")+r.join("linear-gradient(left top,#9f9, white);background-image:")).slice(0,-17);k.cssText=b;return!!~(""+k.backgroundImage).indexOf("gradient")};f.cssreflections=function(){return h("boxReflect")};f.csstransforms=function(){return!!q(["transformProperty","WebkitTransform","MozTransform","OTransform","msTransform"])};f.csstransforms3d=function(){var b=!!q(["perspectiveProperty","WebkitPerspective",
"MozPerspective","OPerspective","msPerspective"]);b&&"webkitPerspective"in j.style&&(b=e.csstransforms3d);return b};f.csstransitions=function(){return h("transitionProperty")};f.fontface=function(){return e.fontface};f.generatedcontent=function(){return e.generatedcontent};f.video=function(){var b=a.createElement("video"),c=!1;try{if(c=!!b.canPlayType)c=new Boolean(c),c.ogg=b.canPlayType('video/ogg; codecs="theora"'),c.h264=b.canPlayType('video/mp4; codecs="avc1.42E01E"')||b.canPlayType('video/mp4; codecs="avc1.42E01E, mp4a.40.2"'),
c.webm=b.canPlayType('video/webm; codecs="vp8, vorbis"')}catch(d){}return c};f.audio=function(){var b=a.createElement("audio"),c=!1;try{if(c=!!b.canPlayType)c=new Boolean(c),c.ogg=b.canPlayType('audio/ogg; codecs="vorbis"'),c.mp3=b.canPlayType("audio/mpeg;"),c.wav=b.canPlayType('audio/wav; codecs="1"'),c.m4a=b.canPlayType("audio/x-m4a;")||b.canPlayType("audio/aac;")}catch(d){}return c};f.localstorage=function(){try{return!!localStorage.getItem}catch(b){return!1}};f.sessionstorage=function(){try{return!!sessionStorage.getItem}catch(b){return!1}};
f.webworkers=function(){return!!c.Worker};f.applicationcache=function(){return!!c.applicationCache};f.svg=function(){return!!a.createElementNS&&!!a.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect};f.inlinesvg=function(){var b=a.createElement("div");b.innerHTML="<svg/>";return"http://www.w3.org/2000/svg"==(b.firstChild&&b.firstChild.namespaceURI)};f.smil=function(){return!!a.createElementNS&&/SVG/.test(x.call(a.createElementNS("http://www.w3.org/2000/svg","animate")))};f.svgclippaths=
function(){return!!a.createElementNS&&/SVG/.test(x.call(a.createElementNS("http://www.w3.org/2000/svg","clipPath")))};for(var v in f)y(f,v)&&(C=v.toLowerCase(),e[C]=f[v](),z.push((e[C]?"":"no-")+C));e.input||g();e.addTest=function(b,a){if("object"==typeof b)for(var c in b)y(b,c)&&e.addTest(c,b[c]);else{b=b.toLowerCase();if(e[b]!==d)return;a="boolean"==typeof a?a:!!a();j.className+=" "+(a?"":"no-")+b;e[b]=a}return e};k.cssText="";f=m=null;c.attachEvent&&function(){var b=a.createElement("div");b.innerHTML=
"<elem></elem>";return 1!==b.childNodes.length}()&&function(b,a){function c(b){for(var a=-1;++a<h;)b.createElement(l[a])}b.iepp=b.iepp||{};var e=b.iepp,f=e.html5elements||"abbr|article|aside|audio|canvas|datalist|details|figcaption|figure|footer|header|hgroup|mark|meter|nav|output|progress|section|summary|time|video",l=f.split("|"),h=l.length,j=RegExp("(^|\\s)("+f+")","gi"),C=RegExp("<(/*)("+f+")","gi"),g=/^\s*[\{\}]\s*$/,m=RegExp("(^|[^\\n]*?\\s)("+f+")([^\\n]*)({[\\n\\w\\W]*?})","gi"),p=a.createDocumentFragment(),
k=a.documentElement,f=k.firstChild,D=a.createElement("body"),y=a.createElement("style"),q=/print|all/,v;e.getCSS=function(b,a){if(b+""===d)return"";for(var c=-1,f=b.length,l,h=[];++c<f;)l=b[c],l.disabled||(a=l.media||a,q.test(a)&&h.push(e.getCSS(l.imports,a),l.cssText),a="all");return h.join("")};e.parseCSS=function(b){for(var a=[],c;null!=(c=m.exec(b));)a.push(((g.exec(c[1])?"\n":c[1])+c[2]+c[3]).replace(j,"$1.iepp_$2")+c[4]);return a.join("\n")};e.writeHTML=function(){var b=-1;for(v=v||a.body;++b<
h;)for(var c=a.getElementsByTagName(l[b]),e=c.length,d=-1;++d<e;)0>c[d].className.indexOf("iepp_")&&(c[d].className+=" iepp_"+l[b]);p.appendChild(v);k.appendChild(D);D.className=v.className;D.id=v.id;D.innerHTML=v.innerHTML.replace(C,"<$1font")};e._beforePrint=function(){y.styleSheet.cssText=e.parseCSS(e.getCSS(a.styleSheets,"all"));e.writeHTML()};e.restoreHTML=function(){D.innerHTML="";k.removeChild(D);k.appendChild(v)};e._afterPrint=function(){e.restoreHTML();y.styleSheet.cssText=""};c(a);c(p);
e.disablePP||(f.insertBefore(y,f.firstChild),y.media="print",y.className="iepp-printshim",b.attachEvent("onbeforeprint",e._beforePrint),b.attachEvent("onafterprint",e._afterPrint))}(c,a);e._version="2.0.6";e._prefixes=r;e._domPrefixes=s;e.mq=function(b){if(c.matchMedia)return matchMedia(b).matches;var a;B("@media "+b+" { #modernizr { position: absolute; } }",function(b){a="absolute"==(c.getComputedStyle?getComputedStyle(b,null):b.currentStyle).position});return a};e.hasEvent=b;e.testProp=function(b){return q([b])};
e.testAllProps=h;e.testStyles=B;e.prefixed=function(b){return h(b,"pfx")};j.className=j.className.replace(/\bno-js\b/,"")+(" js "+z.join(" "));return e}(this,this.document);
(function(c,a){function d(){u(!0)}c.respond={};respond.update=function(){};respond.mediaQueriesSupported=a;if(!a){var g=c.document,h=g.documentElement,q=[],p=[],e=[],j={},f=g.getElementsByTagName("head")[0]||h,k=f.getElementsByTagName("link"),m=[],t=function(){for(var b=k.length,a=0,d,e,f;a<b;a++)d=k[a],e=d.href,f=d.media,d=d.rel&&"stylesheet"===d.rel.toLowerCase(),e&&d&&!j[e]&&(!/^([a-zA-Z]+?:(\/\/)?(www\.)?)/.test(e)||e.replace(RegExp.$1,"").split("/")[0]===c.location.host?m.push({href:e,media:f}):
j[e]=!0);x()},x=function(){if(m.length){var b=m.shift();z(b.href,function(a){r(a,b.href,b.media);j[b.href]=!0;x()})}},r=function(b,a,c){var d=b.match(/@media[^\{]+\{([^\{\}]+\{[^\}\{]+\})+/gi),e=d&&d.length||0,a=a.substring(0,a.lastIndexOf("/")),f=function(b){return b.replace(/(url\()['"]?([^\/\)'"][^:\)'"]+)['"]?(\))/g,"$1"+a+"$2$3")},h=!e&&c,j=0,g,m,k,F,I;a.length&&(a+="/");for(h&&(e=1);j<e;j++){g=0;h?(m=c,p.push(f(b))):(m=d[j].match(/@media ([^\{]+)\{([\S\s]+?)$/)&&RegExp.$1,p.push(RegExp.$2&&
f(RegExp.$2)));F=m.split(",");for(I=F.length;g<I;g++)k=F[g],q.push({media:k.match(/(only\s+)?([a-zA-Z]+)(\sand)?/)&&RegExp.$2,rules:p.length-1,minw:k.match(/\(min\-width:[\s]*([\s]*[0-9]+)px[\s]*\)/)&&parseFloat(RegExp.$1),maxw:k.match(/\(max\-width:[\s]*([\s]*[0-9]+)px[\s]*\)/)&&parseFloat(RegExp.$1)})}u()},s,w,u=function(b){var a=h.clientWidth,c="CSS1Compat"===g.compatMode&&a||g.body.clientWidth||a,a={},d=g.createDocumentFragment(),j=k[k.length-1],m=(new Date).getTime();if(b&&s&&30>m-s)clearTimeout(w),
w=setTimeout(u,30);else{s=m;for(var o in q)if(b=q[o],!b.minw&&!b.maxw||(!b.minw||b.minw&&c>=b.minw)&&(!b.maxw||b.maxw&&c<=b.maxw))a[b.media]||(a[b.media]=[]),a[b.media].push(p[b.rules]);for(o in e)e[o]&&e[o].parentNode===f&&f.removeChild(e[o]);for(o in a)b=g.createElement("style"),c=a[o].join("\n"),b.type="text/css",b.media=o,b.styleSheet?b.styleSheet.cssText=c:b.appendChild(g.createTextNode(c)),d.appendChild(b),e.push(b);f.insertBefore(d,j.nextSibling)}},z=function(b,a){var c=B();c&&(c.open("GET",
b,!0),c.onreadystatechange=function(){4==c.readyState&&(200==c.status||304==c.status)&&a(c.responseText)},4!=c.readyState&&c.send())},B=function(){for(var b=!1,a=[function(){return new ActiveXObject("Microsoft.XMLHTTP")},function(){return new XMLHttpRequest}],c=a.length;c--;){try{b=a[c]()}catch(d){continue}break}return function(){return b}}();t();respond.update=t;c.addEventListener?c.addEventListener("resize",d,!1):c.attachEvent&&c.attachEvent("onresize",d)}})(this,Modernizr.mq("only all"));
(function(c,a,d){function g(){for(var b=1,a=-1;r.length-++a&&(!r[a].s||(b=r[a].r)););b&&p()}function h(b){var c=a.createElement("script"),d;c.src=b.s;c.onreadystatechange=c.onload=function(){!d&&(!c.readyState||"loaded"==c.readyState||"complete"==c.readyState)&&(d=1,g(),c.onload=c.onreadystatechange=null)};m(function(){d||(d=1,g())},A.errorTimeout);b.e?c.onload():t.parentNode.insertBefore(c,t)}function q(c){var d=a.createElement("link"),e;d.href=c.s;d.rel="stylesheet";d.type="text/css";if(!c.e&&(b||
w)){var f=function(b){m(function(){if(!e)try{b.sheet.cssRules.length?(e=1,g()):f(b)}catch(a){1E3==a.code||"security"==a.message||"denied"==a.message?(e=1,m(function(){g()},0)):f(b)}},0)};f(d)}else d.onload=function(){e||(e=1,m(function(){g()},0))},c.e&&d.onload();m(function(){e||(e=1,g())},A.errorTimeout);!c.e&&t.parentNode.insertBefore(d,t)}function p(){var b=r.shift();s=1;b?b.t?m(function(){"c"==b.t?q(b):h(b)},0):(b(),g()):s=0}function e(b,c,d,e,f,h){function j(){!k&&(!l.readyState||"loaded"==l.readyState||
"complete"==l.readyState)&&(n.r=k=1,!s&&g(),l.onload=l.onreadystatechange=null,m(function(){z.removeChild(l)},0))}var l=a.createElement(b),k=0,n={t:d,s:c,e:h};l.src=l.data=c;!u&&(l.style.display="none");l.width=l.height="0";"object"!=b&&(l.type=d);l.onload=l.onreadystatechange=j;"img"==b?l.onerror=j:"script"==b&&(l.onerror=function(){n.e=n.r=1;p()});r.splice(e,0,n);z.insertBefore(l,u?null:t);m(function(){k||(z.removeChild(l),n.r=n.e=k=1,g())},A.errorTimeout)}function j(b,a,c){var d="c"==a?y:l;s=0;
a=a||"j";n(b)?e(d,b,a,this.i++,k,c):(r.splice(this.i++,0,b),1==r.length&&p());return this}function f(){var b=A;b.loader={load:j,i:0};return b}var k=a.documentElement,m=c.setTimeout,t=a.getElementsByTagName("script")[0],x={}.toString,r=[],s=0,w="MozAppearance"in k.style,u=w&&!!a.createRange().compareNode,z=u?k:t.parentNode,B=c.opera&&"[object Opera]"==x.call(c.opera),b="webkitAppearance"in k.style,C=b&&"async"in a.createElement("script"),l=w?"object":B||C?"img":"script",y=b?"img":l,v=Array.isArray||
function(b){return"[object Array]"==x.call(b)},n=function(b){return"string"==typeof b},o=function(b){return"[object Function]"==x.call(b)},E=[],G={},H,A;A=function(b){function a(b){var b=b.split("!"),c=E.length,d=b.pop(),e=b.length,d={url:d,origUrl:d,prefixes:b},f,j;for(j=0;j<e;j++)(f=G[b[j]])&&(d=f(d));for(j=0;j<c;j++)d=E[j](d);return d}function c(b,e,j,h,l){var g=a(b),k=g.autoCallback;if(!g.bypass){e&&(e=o(e)?e:e[b]||e[h]||e[b.split("/").pop().split("?")[0]]);if(g.instead)return g.instead(b,e,j,
h,l);j.load(g.url,g.forceCSS||!g.forceJS&&/css$/.test(g.url)?"c":d,g.noexec);(o(e)||o(k))&&j.load(function(){f();e&&e(g.origUrl,l,h);k&&k(g.origUrl,l,h)})}}function e(b,a){function d(b){if(n(b))c(b,h,a,0,f);else if(Object(b)===b)for(l in b)b.hasOwnProperty(l)&&c(b[l],h,a,l,f)}var f=!!b.test,j=b.load||b.both,h=b.callback,l;d(f?b.yep:b.nope);d(j);b.complete&&a.load(b.complete)}var h,j,l=this.yepnope.loader;if(n(b))c(b,0,l,0);else if(v(b))for(h=0;h<b.length;h++)j=b[h],n(j)?c(j,0,l,0):v(j)?A(j):Object(j)===
j&&e(j,l);else Object(b)===b&&e(b,l)};A.addPrefix=function(b,a){G[b]=a};A.addFilter=function(b){E.push(b)};A.errorTimeout=1E4;null==a.readyState&&a.addEventListener&&(a.readyState="loading",a.addEventListener("DOMContentLoaded",H=function(){a.removeEventListener("DOMContentLoaded",H,0);a.readyState="complete"},0));c.yepnope=f()})(this,this.document);Modernizr.load=function(){yepnope.apply(window,[].slice.call(arguments,0))};window.log=function(){log.history=log.history||[];log.history.push(arguments);this.console&&(arguments.callee=arguments.callee.caller,console.log(Array.prototype.slice.call(arguments)))};(function(c){function a(){}for(var d="assert count debug dir dirxml error exception group groupCollapsed groupEnd info log markTimeline profile profileEnd time timeEnd trace warn".split(" "),g;g=d.pop();)c[g]=c[g]||a})(window.console=window.console||{});
(function(c){var a=0;c.fn.mobileMenu=function(d){function g(d){return d.attr("id")?0<c("#mobileMenu_"+d.attr("id")).length:(a++,d.attr("id","mm"+a),0<c("#mobileMenu_mm"+a).length)}function h(a){a.hide();c("#mobileMenu_"+a.attr("id")).show()}function q(a){if(a.is("ul, ol")){var d='<select id="mobileMenu_'+a.attr("id")+'" class="mobileMenu">',d=d+('<option value="">'+e.topOptionText+"</option>");a.find("li").each(function(){var a="",h=c(this).parents("ul, ol").length;for(i=1;i<h;i++)a+=e.indentString;
h=c(this).find("a:first-child").attr("href");a+=c(this).clone().children("ul, ol").remove().end().text();d+='<option value="'+h+'">'+a+"</option>"});d+="</select>";a.parent().append(d);c("#mobileMenu_"+a.attr("id")).change(function(){var a=c(this);null!==a.val()&&(document.location.href=a.val())});h(a)}else alert("mobileMenu will only work with UL or OL elements!")}function p(a){c(window).width()<e.switchWidth&&!g(a)?q(a):c(window).width()<e.switchWidth&&g(a)?h(a):!(c(window).width()<e.switchWidth)&&
g(a)&&(a.show(),c("#mobileMenu_"+a.attr("id")).hide())}var e={switchWidth:768,topOptionText:"Select a page",indentString:"&nbsp;&nbsp;&nbsp;"};return this.each(function(){d&&c.extend(e,d);var a=c(this);c(window).resize(function(){p(a)});p(a)})}})(jQuery);
(function(c){function a(a,c){for(var d=a,e=0;a=a[c];)d.tagName==a.tagName&&e++;return e}function d(c,d,g){c=a(c,g);if("odd"==d||"even"==d)g=2,c-="odd"!=d;else{var e=d.indexOf("n");-1<e?(g=parseInt(d,10)||parseInt(d.substring(0,e)+"1",10),c-=(parseInt(d.substring(e+1),10)||0)-1):(g=c+1,c-=parseInt(d,10)-1)}return(0>g?0>=c:0<=c)&&0==c%g}var g={"first-of-type":function(c){return 0==a(c,"previousSibling")},"last-of-type":function(c){return 0==a(c,"nextSibling")},"only-of-type":function(a){return g["first-of-type"](a)&&
g["last-of-type"](a)},"nth-of-type":function(a,c,g){return d(a,g[3],"previousSibling")},"nth-last-of-type":function(a,c,g){return d(a,g[3],"nextSibling")}};c.extend(c.expr[":"],g)})(jQuery);
(function(c,a,d){function g(a){var c={},f=/^jQuery\d+$/;d.each(a.attributes,function(a,d){d.specified&&!f.test(d.name)&&(c[d.name]=d.value)});return c}function h(){var a=d(this);a.val()===a.attr("placeholder")&&a.hasClass("placeholder")&&(a.data("placeholder-password")?a.hide().next().show().focus().attr("id",a.removeAttr("id").data("placeholder-id")):a.val("").removeClass("placeholder"))}function q(){var a,c=d(this),f=this.id;if(""===c.val()){if(c.is(":password")){if(!c.data("placeholder-textinput")){try{a=
c.clone().attr({type:"text"})}catch(k){a=d("<input>").attr(d.extend(g(this),{type:"text"}))}a.removeAttr("name").data("placeholder-password",!0).data("placeholder-id",f).bind("focus.placeholder",h);c.data("placeholder-textinput",a).data("placeholder-id",f).before(a)}c=c.removeAttr("id").hide().prev().attr("id",f).show()}c.addClass("placeholder").val(c.attr("placeholder"))}else c.removeClass("placeholder")}var p="placeholder"in a.createElement("input"),a="placeholder"in a.createElement("textarea");
p&&a?(d.fn.placeholder=function(){return this},d.fn.placeholder.input=d.fn.placeholder.textarea=!0):(d.fn.placeholder=function(){return this.filter((p?"textarea":":input")+"[placeholder]").bind("focus.placeholder",h).bind("blur.placeholder",q).trigger("blur.placeholder").end()},d.fn.placeholder.input=p,d.fn.placeholder.textarea=a,d(function(){d("form").bind("submit.placeholder",function(){var a=d(".placeholder",this).each(h);setTimeout(function(){a.each(q)},10)})}),d(c).bind("unload.placeholder",
function(){d(".placeholder").val("")}))})(this,document,jQuery);(function(c){window.MBP=window.MBP||{};MBP.viewportmeta=c.querySelector&&c.querySelector('meta[name="viewport"]');MBP.ua=navigator.userAgent;MBP.scaleFix=function(){MBP.viewportmeta&&(/iPhone|iPad/.test(MBP.ua)&&!/Opera Mini/.test(MBP.ua))&&(MBP.viewportmeta.content="width=device-width, minimum-scale=1.0, maximum-scale=1.0",c.addEventListener("gesturestart",MBP.gestureStart,!1))};MBP.gestureStart=function(){MBP.viewportmeta.content="width=device-width, minimum-scale=0.25, maximum-scale=1.6"};MBP.hideUrlBar=
function(){/iPhone/.test(MBP.ua)&&!pageYOffset&&!location.hash&&setTimeout(function(){window.scrollTo(0,1)},1E3)};MBP.fastButton=function(a,c){this.element=a;this.handler=c;a.addEventListener&&(a.addEventListener("touchstart",this,!1),a.addEventListener("click",this,!1))};MBP.fastButton.prototype.handleEvent=function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onClick(a);break;case "click":this.onClick(a)}};MBP.fastButton.prototype.onTouchStart=
function(a){a.stopPropagation();this.element.addEventListener("touchend",this,!1);c.body.addEventListener("touchmove",this,!1);this.startX=a.touches[0].clientX;this.startY=a.touches[0].clientY;this.element.style.backgroundColor="rgba(0,0,0,.7)"};MBP.fastButton.prototype.onTouchMove=function(a){(10<Math.abs(a.touches[0].clientX-this.startX)||10<Math.abs(a.touches[0].clientY-this.startY))&&this.reset()};MBP.fastButton.prototype.onClick=function(a){a.stopPropagation();this.reset();this.handler(a);"touchend"==
a.type&&MBP.preventGhostClick(this.startX,this.startY);this.element.style.backgroundColor=""};MBP.fastButton.prototype.reset=function(){this.element.removeEventListener("touchend",this,!1);c.body.removeEventListener("touchmove",this,!1);this.element.style.backgroundColor=""};MBP.preventGhostClick=function(a,c){MBP.coords.push(a,c);window.setTimeout(function(){MBP.coords.splice(0,2)},2500)};MBP.ghostClickHandler=function(a){for(var c=0,g=MBP.coords.length;c<g;c+=2){var h=MBP.coords[c+1];25>Math.abs(a.clientX-
MBP.coords[c])&&25>Math.abs(a.clientY-h)&&(a.stopPropagation(),a.preventDefault())}};c.addEventListener&&c.addEventListener("click",MBP.ghostClickHandler,!0);MBP.coords=[];MBP.splash=function(){c.write('<link rel="apple-touch-startup-image" href="/img/'+("iPad"===navigator.platform?"h/":"l/")+'splash.png" />')};MBP.autogrow=function(a,c){function g(){var a=this.scrollHeight;a>this.clientHeight&&(this.style.height=a+3*q+"px")}var h=c?c:12,q=a.currentStyle?a.currentStyle.lineHeight:getComputedStyle(a,
null).lineHeight,q=-1==q.indexOf("px")?h:parseInt(q,10);a.style.overflow="hidden";a.addEventListener?a.addEventListener("keyup",g,!1):a.attachEvent("onkeyup",g)}})(document);$(document).ready(function(){$.fn.mobileMenu&&$("ol#id").mobileMenu({switchWidth:768,topOptionText:"Choose a page",indentString:"&nbsp;&nbsp;&nbsp;"});$.fn.placeholder&&$("input, textarea").placeholder()});(function(c,a){function d(){u(!0)}c.respond={};respond.update=function(){};respond.mediaQueriesSupported=a;if(!a){var g=c.document,h=g.documentElement,q=[],p=[],e=[],j={},f=g.getElementsByTagName("head")[0]||h,k=f.getElementsByTagName("link"),m=[],t=function(){for(var b=k.length,a=0,d,e,f,g;a<b;a++)d=k[a],e=d.href,f=d.media,g=d.rel&&"stylesheet"===d.rel.toLowerCase(),e&&(g&&!j[e])&&(d.styleSheet&&d.styleSheet.rawCssText?(r(d.styleSheet.rawCssText,e,f),j[e]=!0):(!/^([a-zA-Z]+?:(\/\/)?)/.test(e)||e.replace(RegExp.$1,
"").split("/")[0]===c.location.host)&&m.push({href:e,media:f}));x()},x=function(){if(m.length){var b=m.shift();z(b.href,function(a){r(a,b.href,b.media);j[b.href]=!0;x()})}},r=function(b,a,c){var d=b.match(/@media[^\{]+\{([^\{\}]+\{[^\}\{]+\})+/gi),e=d&&d.length||0,a=a.substring(0,a.lastIndexOf("/")),f=function(b){return b.replace(/(url\()['"]?([^\/\)'"][^:\)'"]+)['"]?(\))/g,"$1"+a+"$2$3")},g=!e&&c,h=0,j,k,m,r;a.length&&(a+="/");for(g&&(e=1);h<e;h++){j=0;g?(k=c,p.push(f(b))):(k=d[h].match(/@media ([^\{]+)\{([\S\s]+?)$/)&&
RegExp.$1,p.push(RegExp.$2&&f(RegExp.$2)));m=k.split(",");for(r=m.length;j<r;j++)k=m[j],q.push({media:k.match(/(only\s+)?([a-zA-Z]+)(\sand)?/)&&RegExp.$2,rules:p.length-1,minw:k.match(/\(min\-width:[\s]*([\s]*[0-9]+)px[\s]*\)/)&&parseFloat(RegExp.$1),maxw:k.match(/\(max\-width:[\s]*([\s]*[0-9]+)px[\s]*\)/)&&parseFloat(RegExp.$1)})}u()},s,w,u=function(b){var a=h.clientWidth,c="CSS1Compat"===g.compatMode&&a||g.body.clientWidth||a,a={},d=g.createDocumentFragment(),j=k[k.length-1],m=(new Date).getTime();
if(b&&s&&30>m-s)clearTimeout(w),w=setTimeout(u,30);else{s=m;for(var o in q)if(b=q[o],!b.minw&&!b.maxw||(!b.minw||b.minw&&c>=b.minw)&&(!b.maxw||b.maxw&&c<=b.maxw))a[b.media]||(a[b.media]=[]),a[b.media].push(p[b.rules]);for(o in e)e[o]&&e[o].parentNode===f&&f.removeChild(e[o]);for(o in a)b=g.createElement("style"),c=a[o].join("\n"),b.type="text/css",b.media=o,b.styleSheet?b.styleSheet.cssText=c:b.appendChild(g.createTextNode(c)),d.appendChild(b),e.push(b);f.insertBefore(d,j.nextSibling)}},z=function(a,
c){var d=B();d&&(d.open("GET",a,!0),d.onreadystatechange=function(){4!=d.readyState||200!=d.status&&304!=d.status||c(d.responseText)},4!=d.readyState&&d.send(null))},B=function(){var a=!1;try{a=new XMLHttpRequest}catch(c){a=new ActiveXObject("Microsoft.XMLHTTP")}return function(){return a}}();t();respond.update=t;c.addEventListener?c.addEventListener("resize",d,!1):c.attachEvent&&c.attachEvent("onresize",d)}})(this,function(c){if(c.matchMedia)return!0;var a,d=document,c=d.documentElement;a=c.firstElementChild||
c.firstChild;var g=!d.body,h=d.body||d.createElement("body"),d=d.createElement("div");d.id="mq-test-1";d.style.cssText="position:absolute;top:-99em";h.appendChild(d);d.innerHTML='_<style media="only all"> #mq-test-1 { width: 9px; }</style>';g&&c.insertBefore(h,a);d.removeChild(d.firstChild);a=9==d.offsetWidth;g?c.removeChild(h):h.removeChild(d);return a}(this));
